version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
    dependencies:
      pre:
        - mkdir $ANDROID_HOME/licenses
        - cat android-sdk-license > $ANDROID_HOME/licenses/android-sdk-license
    JVM_OPTS: -Xmx3200m
    steps:
        - checkout
      #  - run:
      #    name: Download Dependencies
      #    command: ./gradlew androidDependencies
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #  - run:
      #    name: Run Tests
      #    command: ./gradlew lint test
      #  - store_artifacts:
      #    path: app/build/reports
      #    destination: reports
      #  - store_test_results:
      #    path: app/build/test-results
