version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
    dependencies:
      pre:
        - mkdir $ANDROID_HOME/licenses
        - cat android-sdk-license > $ANDROID_HOME/licenses/android-sdk-license
    JVM_OPTS: -Xmx3200m
    steps:
        - checkout
        - run:
            name: Build
            command: ./gradlew clean build
        - run:
            name: Run Tests
            command: ./gradlew lint test
  deploy:
    machine:
      enabled:true
    working_directory: ~/code
    steps:
      - run:
        command:
          - ./gradlew assembleDebug
          -  curl -F "file=@app/build/outputs/apk/app-release-unsigned.apk" -F "token=${DEPLOY_GATE_API_KEY}" -F "message=sample" https://deploygate.com/api/users/moroku0519/apps

workflow:
  version2:
    build-and-deploy:
      jobs:
        - build
        - deploy:
          require:
            - build
          filter:
            branches:
              only: develop
